### ISSUE TITLE
Create script to determine phase angles and stimulation strength

### ISSUE THREAD

**Issue by KTZ228** [Donders-Institute/PRESTUS#11]
Since it is impossible to simulate the acoustic properties of all materials that make up an actual transducer we approach its intensity profile (provided in the calibration report) with virtual transducer elements. This is why parameters such as the phase angles [source_phase_deg] and stimulation strength [source_amp] provided by the manufacturer can not be directly fed into our simulations. 
Currently, this is done by running through the steps found in the tutorial.

A better solution would be to have a script that can use the intensity curves at multiple focus_distance settings and with a target of peak stimulation strength [Isppa in free water] and gives you the parameters necessary for use in the config file.

This script has to be easy to use and provide easy-to-interpret results for the user since not having correctly recreated your transducer means all results are worthless (possibly without the experimenter knowing).

**Comment by KTZ228** [comment]
In terms of input, I was thinking about using:
- A csv file with multiple columns as input so that the parameters for multiple focus_distance settings can be calculated at once
- Use the config file as input so that the phase angles are based on the transducer's dimensions and the sizes of each individual element.
- An output location to save the csv file containing the output and water simulation results as a control.

In terms of output:
- A graph (as seen in the tutorial) showing how closely your simulated transducer mimics the actual profile.
- Results from water simulations as an additional control.
- A csv containing the parameters needed to reach the focus_distance and stimulation strength.

**Comment by mekman** [comment]
closing this in favor of #32
