### ISSUE TITLE
[bug] max. CEM43 = 0

### ISSUE THREAD

**Issue by jkosciessa** [Donders-Institute/PRESTUS#45]
This affects the currently unmerged `updated` branch in https://github.com/Donders-Institute/PRESTUS/pull/34. 

The simulations run successfully, including calculation of CEM43 metrics, but the output table always codes CEM43 as 0. Can you take a look @sirmrmarty?

![sub-001_layered_CEM_by_time_left_MD_duty_20_trials_3200](https://github.com/Donders-Institute/PRESTUS/assets/40263608/8a9b8965-ce45-4610-9c7b-4bd8ca8bc8e9)
[sub-001_layered_output_table_left_MD_duty_20_trials_3200.csv](https://github.com/user-attachments/files/15836107/sub-001_layered_output_table_left_MD_duty_20_trials_3200.csv)

[I also wonder why we obtain max. ISPPA of 45 W/cm2 with free-water output of max. 40 W/cm2]

**Comment by sirmrmarty** [comment]
I fix the bug and commit it into your branch
